name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: Checkout
          uses: actions/checkout@v2.4.2
        - name: run_bash
          run: bash run.sh
        - name: add_commit
          run: |
            git config --global user.email "1171686724@qq.com"
            git config --global user.name "DuskyJuniXor"
            git checkout -b sidepath
            git pull origin master --allow-unrelated-histories
            git checkout master
            git branch
            git merge sidepath
            git push origin master --allow-unrelated-histories
