name: action1
on: [push]
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - id: step1
          run: |
            sudo apt-get update
            sudo apt-get install gcc:9.4.0
        - id: step2
          run: |
            #cd TheSelf-cultivationOfTheLazy
            #chmod +x run.sh
            bash run.sh
            #echo "::set-output name=result::$(bash run.sh)"
        - id: case1
          run: |
            git switch master
            git merge dev
            git push -u origin master
