name: action1
on:
  commit:
    branches:
      - dev
jobs:
  myjob
    name: myjob
      runs-on: ubuntu-20.04
      outputs:
        output: ${{steps.step2.outputs.result}}
      steps:
        - id: step1
          run: sudo apt-get install gcc:9.4.0
        - id: step2
          run: bash run.sh
          run: ::set-output name=result::`bash run.sh`
        - id: case1:
          run: |
            if [ ${{result}}=="TEST PASS" ]
            then
              git add .
              git commit -m "newer version"
              git switch master
              git merge dev
              git push -u origin master
        - id: case2:
          run: |
            if [ ${{result}}=="TEST FAILED" ]
            then exit(1)
