name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: automation
          run: |
            git config --global user.name "DuskyJuniXor"
            git config --global user.password "DY-20050206-dkj"
            git config --global user.password "1171686724@qq.com"
            git clone git@github.com:DuskyJuniXor/TheSelf-cultivationOfTheLazy.git
            git branch
            git switch master
            git merge dev
            git push -u origin master
