name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: Checkout
          uses: actions/checkout@v2.4.2
          with:
            token: ${{ github.token }}
        - name: merge&push
          run: |
            git config --global user.email "1171686724@qq.com"
            git config --global user.name "DuskyJuniXor"
            result=`bash run.sh`
            if ["$result" == "TEST PASS"]
              then
                git push origin dev:master -f
                git reset --hard origin/master
            else
                exit(0)
            fi
