name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: automation
          run: |
            git config --global user.name "DuskyJuniXor"
            git config --global user.email "1171686724@qq.com"
            git config --global http.sslVerify "false"
            git init
            git clone https://github.com/DuskyJuniXor/TheSelf-cultivationOfTheLazy.git
            remote_addr=`git remote get-url --push origin`
            remote_addr=`echo $remote_addr|  awk -F'://' '{print $2}'`
            remote_addr=https://${user_name}:${{ secrets.GITHUB_TOKEN }}@${remote_addr}
            git remote add origin ${remote_addr}
            cd /home/runner/work/TheSelf-cultivationOfTheLazy/TheSelf-cultivationOfTheLazy
            git fetch origin dev
            git fetch origin master
            git checkout master
            git merge origin/dev
            git push origin HEAD --force
