name: action1
on: [push]
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - id: step1
          uses: egor-tensin/setup-gcc@v1
          with:
            version: 9.4.0    
        - id: step2
          run: |
            cd /TheSelf-cultivationOfTheLazy
            chmod +x run.sh
            bash run.sh
#            echo "::set-output name=result::$(bash run.sh)"
#        - id: case1
#          if：contains($(run.sh), 'PASS')
         - id: step3
            run: |
              git switch master
              git merge dev
              git push -u origin master
#        - id: case2
#          run: |
#            if: `bash run.sh`
#            run: exit(1)
