name: action1
on: [push]
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - id: step1
          uses: egor-tensin/setup-gcc@v1
          with:
            version: 9.4.0    
        - id: step2
          run: chmod +x run.sh
        - id: case1
          run: |
            if [ ${{`bash run.sh`}} == "TEST PASS" ]
            then
              git switch master
              git merge dev
              git push -u origin master
            fi
        - id: case2
          run: |
            if [ ${{bash run.sh`}} == "TEST FAILED" ]
            then exit(1)
            fi
