name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: Checkout
          uses: actions/checkout@v2.4.2
          with:
            token: ${{ github.token }}
        - name: merge
          run: |
            git branch
            git push
            git checkout master
            git pull 
            git merge dev
            git push origin master
