name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: automation
          run: |
            git config --global user.name "DuskyJuniXor"
            git config --global user.email "1171686724@qq.com"
            git config --global http.sslVerify "false"
            git init
            git clone https://github.com/DuskyJuniXor/TheSelf-cultivationOfTheLazy.git
            git remote add origin https://DuskyJuniXor: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@github.com/DuskyJuniXor/TheSelf-cultivationOfTheLazy.git
            cd /home/runner/work/TheSelf-cultivationOfTheLazy/TheSelf-cultivationOfTheLazy
            git fetch origin dev
            git fetch origin master
            git checkout master
            git merge origin/dev
            git push origin HEAD --force
