name: action_dev
on: 
  push:
    branches:
      - dev
jobs:
  myjob:
      runs-on: ubuntu-20.04
      steps:
        - name: install_gcc
          run: |
            sudo apt-get update
            sudo apt-get install gcc
        - name: Checkout
          uses: actions/checkout@v2.4.2
        - name: run_bash
          run: bash run.sh
        - name: add_commit
          run: |
            git config --global user.email "1171686724@qq.com"
            git config --global user.name "DuskyJuniXor"
        - name: Merge pull requests (automerge-action)
          uses: pascalgn/automerge-action@v0.15.3
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
